export const mockActivities = [
  // ========== JAIPUR ==========
  {
    id: 1,
    name: 'Amber Fort Exploration',
    city: 'Jaipur',
    image: 'https://images.unsplash.com/photo-1587474267362-4e5f6e2f7a4c?w=600',
    rating: 4.9,
    cost: 500,
    duration: '3 hours',
    category: 'Historical',
    description: 'Elephant ride, mirror palace, and panoramic views of Jaipur.',
    favorite: false,
  },
  {
    id: 2,
    name: 'Hawa Mahal & City Palace Walk',
    city: 'Jaipur',
    image: 'https://images.unsplash.com/photo-1599661046289-e8c1d8f6a8c7?w=600',
    rating: 4.7,
    cost: 300,
    duration: '2 hours',
    category: 'Historical',
    description: 'Iconic pink facade and royal palace complex.',
    favorite: true,
  },
  {
    id: 3,
    name: 'Jaipur Street Food Tour',
    city: 'Jaipur',
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=600',
    rating: 4.9,
    cost: 800,
    duration: '3 hours',
    category: 'Food',
    description: 'Try dal baati churma, pyaaz kachori, and lassi.',
    favorite: false,
  },
  // ========== GOA ==========
  {
    id: 4,
    name: 'Baga Beach & Watersports',
    city: 'Goa',
    image: 'https://images.unsplash.com/photo-1512343879784-a5bf2cdd8e7b?w=600',
    rating: 4.8,
    cost: 1500,
    duration: '4 hours',
    category: 'Adventure',
    description: 'Parasailing, jet skiing, and banana boat rides.',
    favorite: false,
  },
  {
    id: 5,
    name: 'Old Goa Churches Tour',
    city: 'Goa',
    image: 'https://images.unsplash.com/photo-1590779030700-812e1b7b5b6f?w=600',
    rating: 4.6,
    cost: 200,
    duration: '2 hours',
    category: 'Historical',
    description: 'Basilica of Bom Jesus and Se Cathedral.',
    favorite: true,
  },
  // ========== KERALA ==========
  {
    id: 6,
    name: 'Houseboat Cruise in Alleppey',
    city: 'Kerala Backwaters',
    image: 'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=600',
    rating: 4.9,
    cost: 3500,
    duration: 'Full day',
    category: 'Nature',
    description: 'Luxury houseboat with Kerala meals and backwater views.',
    favorite: true,
  },
  {
    id: 7,
    name: 'Kathakali Dance Performance',
    city: 'Kerala Backwaters',
    image: 'https://images.unsplash.com/photo-1605296867424-35fc25c6e5c5?w=600',
    rating: 4.7,
    cost: 400,
    duration: '1.5 hours',
    category: 'Cultural',
    description: 'Traditional Kerala dance-drama with elaborate makeup.',
    favorite: false,
  },
  // ========== VARANASI ==========
  {
    id: 8,
    name: 'Ganga Aarti at Dashashwamedh Ghat',
    city: 'Varanasi',
    image: 'https://images.unsplash.com/photo-1587474267362-4e5f6e2f7a4c?w=600',
    rating: 4.9,
    cost: 0,
    duration: '1 hour',
    category: 'Spiritual',
    description: 'Evening prayer ceremony with lamps and chanting.',
    favorite: true,
  },
  {
    id: 9,
    name: 'Boat Ride at Sunrise',
    city: 'Varanasi',
    image: 'https://images.unsplash.com/photo-1585123334904-8450d5c3d6e4?w=600',
    rating: 4.8,
    cost: 300,
    duration: '1 hour',
    category: 'Nature',
    description: 'View the ghats and cremation sites from the Ganges.',
    favorite: false,
  },
  // ========== MANALI ==========
  {
    id: 10,
    name: 'Solang Valley Paragliding',
    city: 'Manali',
    image: 'https://images.unsplash.com/photo-1626621341517-bbf1d9999a2b?w=600',
    rating: 4.8,
    cost: 2500,
    duration: '30 mins',
    category: 'Adventure',
    description: 'Fly over snow-capped peaks and valleys.',
    favorite: false,
  },
  {
    id: 11,
    name: 'Hadimba Temple Visit',
    city: 'Manali',
    image: 'https://images.unsplash.com/photo-1602859071840-5edc0e9c8f2d?w=600',
    rating: 4.5,
    cost: 50,
    duration: '1 hour',
    category: 'Spiritual',
    description: 'Ancient cave temple surrounded by deodar forest.',
    favorite: true,
  },
  // ========== MUMBAI ==========
  {
    id: 12,
    name: 'Marine Drive Sunset Walk',
    city: 'Mumbai',
    image: 'https://images.unsplash.com/photo-1568393691622-c7ba131dffb4?w=600',
    rating: 4.7,
    cost: 0,
    duration: '1.5 hours',
    category: 'Nature',
    description: "Queen's Necklace – iconic promenade with Arabian Sea view.",
    favorite: false,
  },
  {
    id: 13,
    name: 'Bollywood Studio Tour',
    city: 'Mumbai',
    image: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=600',
    rating: 4.6,
    cost: 1200,
    duration: '4 hours',
    category: 'Entertainment',
    description: 'Behind-the-scenes of a film shooting and dance workshop.',
    favorite: true,
  },
  // ========== UDAIPUR ==========
  {
    id: 14,
    name: 'Lake Pichola Boat Ride',
    city: 'Udaipur',
    image: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?w=600',
    rating: 4.9,
    cost: 400,
    duration: '45 mins',
    category: 'Nature',
    description: 'Jag Mandir and City Palace views from the lake.',
    favorite: false,
  },
  {
    id: 15,
    name: 'Bagore-ki-Haveli Cultural Show',
    city: 'Udaipur',
    image: 'https://images.unsplash.com/photo-1590779030700-812e1b7b5b6f?w=600',
    rating: 4.8,
    cost: 250,
    duration: '2 hours',
    category: 'Cultural',
    description: 'Traditional Rajasthani puppet show and dance.',
    favorite: true,
  },
]

export const activityCategories = [
  { id: 'historical', name: 'Historical', icon: 'Landmark', color: 'bg-amber-100 text-amber-700' },
  { id: 'food', name: 'Food', icon: 'Utensils', color: 'bg-orange-100 text-orange-700' },
  { id: 'adventure', name: 'Adventure', icon: 'Mountain', color: 'bg-green-100 text-green-700' },
  { id: 'nature', name: 'Nature', icon: 'Trees', color: 'bg-emerald-100 text-emerald-700' },
  { id: 'cultural', name: 'Cultural', icon: 'Theater', color: 'bg-purple-100 text-purple-700' },
  { id: 'spiritual', name: 'Spiritual', icon: 'Church', color: 'bg-indigo-100 text-indigo-700' },
  { id: 'entertainment', name: 'Entertainment', icon: 'Clapperboard', color: 'bg-pink-100 text-pink-700' },
  { id: 'shopping', name: 'Shopping', icon: 'ShoppingBag', color: 'bg-rose-100 text-rose-700' },
  { id: 'relax', name: 'Relax', icon: 'Coffee', color: 'bg-slate-100 text-slate-700' },
]
