export const mockCities = [
  // ========== INDIAN CITIES ==========
  {
    id: 1,
    name: 'Jaipur',
    country: 'India',
    image: 'https://images.unsplash.com/photo-1599661046289-e8c1d8f6a8c7?w=600',
    popularity: 95,
    avgCost: 4500,
    climate: 'Semi-arid',
    description: 'The Pink City – palaces, forts, and vibrant bazaars.',
    weather: '28°C Sunny',
    budget: 'medium',
  },
  {
    id: 2,
    name: 'Kerala Backwaters',
    country: 'India',
    image: 'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=600',
    popularity: 94,
    avgCost: 3500,
    climate: 'Tropical',
    description: 'Serene houseboats, lush greenery, and Ayurveda.',
    weather: '26°C Humid',
    budget: 'medium',
  },
  {
    id: 3,
    name: 'Goa',
    country: 'India',
    image: 'https://images.unsplash.com/photo-1512343879784-a5bf2cdd8e7b?w=600',
    popularity: 98,
    avgCost: 4000,
    climate: 'Tropical',
    description: 'Beaches, nightlife, and Portuguese heritage.',
    weather: '30°C Sunny',
    budget: 'medium',
  },
  {
    id: 4,
    name: 'Manali',
    country: 'India',
    image: 'https://images.unsplash.com/photo-1626621341517-bbf1d9999a2b?w=600',
    popularity: 92,
    avgCost: 3500,
    climate: 'Mountain',
    description: 'Himalayan adventure – snow, rivers, and pine forests.',
    weather: '15°C Clear',
    budget: 'low',
  },
  {
    id: 5,
    name: 'Varanasi',
    country: 'India',
    image: 'https://images.unsplash.com/photo-1587474267362-4e5f6e2f7a4c?w=600',
    popularity: 88,
    avgCost: 2500,
    climate: 'Subtropical',
    description: 'Spiritual capital of India – Ganga Aarti and ancient ghats.',
    weather: '32°C Hot',
    budget: 'low',
  },
  {
    id: 6,
    name: 'Udaipur',
    country: 'India',
    image: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?w=600',
    popularity: 93,
    avgCost: 5000,
    climate: 'Semi-arid',
    description: 'City of Lakes – romantic palaces and sunset views.',
    weather: '27°C Sunny',
    budget: 'high',
  },
  {
    id: 7,
    name: 'Andaman Islands',
    country: 'India',
    image: 'https://images.unsplash.com/photo-1581235725073-8a3e0f6f5b5f?w=600',
    popularity: 91,
    avgCost: 6000,
    climate: 'Tropical',
    description: 'Crystal clear waters, coral reefs, and white sands.',
    weather: '28°C Humid',
    budget: 'high',
  },
  {
    id: 8,
    name: 'Mumbai',
    country: 'India',
    image: 'https://images.unsplash.com/photo-1568393691622-c7ba131dffb4?w=600',
    popularity: 97,
    avgCost: 5500,
    climate: 'Tropical',
    description: 'City of dreams – Bollywood, Gateway of India, and street food.',
    weather: '30°C Sunny',
    budget: 'high',
  },
  // ========== INTERNATIONAL ==========
  {
    id: 9,
    name: 'Bali',
    country: 'Indonesia',
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=600',
    popularity: 99,
    avgCost: 10000,
    climate: 'Tropical',
    description: 'Rice terraces, beaches, and volcanic landscapes.',
    weather: '28°C Sunny',
    budget: 'medium',
  },
  {
    id: 10,
    name: 'Dubai',
    country: 'UAE',
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=600',
    popularity: 96,
    avgCost: 15000,
    climate: 'Arid',
    description: 'Modern skyscrapers, luxury shopping, and desert safaris.',
    weather: '35°C Hot',
    budget: 'high',
  },
]
