export const mockTrips = [
  {
    id: 1,
    name: 'Jaipur – The Pink City',
    destination: 'India',
    startDate: '2026-09-05',
    endDate: '2026-09-15',
    coverImage: 'https://images.pexels.com/photos/16534739/pexels-photo-16534739.jpeg',
    budget: 125000,
    spent: 0,
    travelers: 4,
    status: 'upcoming',
    description: 'Exploring the royal forts and vibrant bazaars of Jaipur.',
    privacy: 'private',
    currency: 'INR',
    category: 'family',
  },
  {
    id: 2,
    name: 'Kerala Backwaters',
    destination: 'India',
    startDate: '2026-10-10',
    endDate: '2026-10-20',
    coverImage: 'https://images.pexels.com/photos/1007565/pexels-photo-1007565.jpeg?w=600',
    budget: 85000,
    spent: 0,
    travelers: 4,
    status: 'upcoming',
    description: 'Serene houseboat rides through the lush Kerala backwaters.',
    privacy: 'private',
    currency: 'INR',
    category: 'family',
  },
  {
    id: 3,
    name: 'Goa Beach Escape',
    destination: 'India',
    startDate: '2026-11-01',
    endDate: '2026-11-07',
    coverImage: 'https://images.pexels.com/photos/28654127/pexels-photo-28654127.jpeg',
    budget: 60000,
    spent: 0,
    travelers: 6,
    status: 'upcoming',
    description: 'Sun, sand, and seafood on the beaches of Goa.',
    privacy: 'public',
    currency: 'INR',
    category: 'friends',
  },
  {
    id: 4,
    name: 'Manali Mountain Retreat',
    destination: 'India',
    startDate: '2026-12-15',
    endDate: '2026-12-22',
    coverImage: 'https://images.pexels.com/photos/1603650/pexels-photo-1603650.jpeg?w=600',
    budget: 95000,
    spent: 0,
    travelers: 5,
    status: 'upcoming',
    description: 'Snow-capped peaks and adventure sports in Manali.',
    privacy: 'private',
    currency: 'INR',
    category: 'friends',
  },
  {
    id: 5,
    name: 'Varanasi Spiritual Walk',
    destination: 'India',
    startDate: '2026-07-20',
    endDate: '2026-07-25',
    coverImage: 'https://images.pexels.com/photos/2387871/pexels-photo-2387871.jpeg?w=600',
    budget: 25000,
    spent: 25000,
    travelers: 2,
    status: 'completed',
    description: 'A soulful journey through the ghats and temples of Varanasi.',
    privacy: 'private',
    currency: 'INR',
    category: 'solo',
  },
  {
    id: 6,
    name: 'Andaman Islands',
    destination: 'India',
    startDate: '2026-07-20',
    endDate: '2026-07-28',
    coverImage: 'https://images.pexels.com/photos/2802292/pexels-photo-2802292.jpeg?w=600',
    budget: 110000,
    spent: 55000,
    travelers: 4,
    status: 'ongoing',
    description: 'Crystal-clear waters and pristine beaches of the Andaman Islands.',
    privacy: 'public',
    currency: 'INR',
    category: 'family',
  },
]

export const mockStats = {
  totalTrips: 6,
  upcomingTrips: 4,
  budgetSpent: 80000,
  citiesVisited: 6,
}
